export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const CREATE_COMPLAIN_SUCCESS = 'CREATE_COMPLAIN_SUCCESS';
export const UPDATE_COMPLAIN_SUCCESS = 'UPDATE_COMPLAIN_SUCCESS';
export const SHOW_COMPLAIN_SUCCESS = 'SHOW_COMPLAIN_SUCCESS';
export const REMOVE_CURRENT_COMPLAIN_SELECTION = 'REMOVE_CURRENT_COMPLAIN_SELECTION';
export const GET_ALL_COMPLAIN_SUCCESS = 'GET_ALL_COMPLAIN_SUCCESS';
